package com.crimsoncrips.borninconfiguration.config;

import static com.mojang.text2speech.Narrator.LOGGER;

public class BIConfig {
    public static boolean SKELETON_BOMB_SPAWNING_ENABLED = true;
    public static boolean DECAYING_ZOMBIE_SPAWNING_ENABLED = true;
    public static boolean BABY_SKELETON_SPAWNING_ENABLED = true;
    public static boolean ZOMBIE_BARREL_SPAWNING_ENABLED = true;
    public static boolean PHANTOM_CREEPER_SPAWNING_ENABLED = true;
    public static boolean DOOR_KNIGHT_SPAWNING_ENABLED = true;
    public static boolean RESTLESS_SPIRIT_SPAWNING_ENABLED = true;
    public static boolean SKELETON_THRASHER_SPAWNING_ENABLED = true;
    public static boolean FIRELIGHT_SPAWNING_ENABLED = true;
    public static boolean BONES_CALLER_SPAWNING_ENABLED = true;
    public static boolean BONE_IMP_SPAWNING_ENABLED = true;
    public static boolean DARK_VORTEX_SPAWNING_ENABLED = true;
    public static boolean DREADHOUND_SPAWNING_ENABLED = true;
    public static boolean FALLEN_CHAOS_KNIGHT_SPAWNING_ENABLED = true;
    public static boolean SER_PUMPKIN_HEAD_SPAWNING_ENABLED = true;
    public static boolean ZOMBIE_CLOWN_SPAWNING_ENABLED = true;
    public static boolean SPIRIT_GUIDE_SPAWNING_ENABLED = true;

    public static boolean CORPSE_FLY_SPAWN_ENABLED = true;
    public static boolean BLOODY_GADFLY_SPAWNING_ENABLED = true;
    public static boolean CORPSE_FISH_SPAWNING_ENABLED = true;
    public static boolean ZOMBIE_FISHERMAN_SPAWNING_ENABLED = true;
    public static boolean THORNSHELL_SPAWNING_ENABLED = true;
    public static boolean GLUTTON_FISH_SPAWNING_ENABLED = true;

    public static boolean ZOMBIE_BRUISER_SPAWNING_ENABLED = true;
    public static boolean MAGGOTS_APPEARANCE_ENABLED = true;
    public static boolean ZOMBIE_LUMBERJACK_SPAWNING_ENABLED = true;
    public static boolean MISSIONER_SPAWNING_ENABLED = true;
    public static boolean FIRE_WELL_GENERATION_ENABLED = true;
    public static boolean OBSERVATION_TOWER_GENERATION_ENABLED = true;
    public static boolean DARK_TOWER_GENERATION_ENABLED = true;
    public static boolean FARM_GENERATION_ENABLED = true;
    public static boolean CLOWN_TENT_GENERATION_ENABLED = true;
    public static boolean SPIRIT_DISSAPPEAR_IN_SUN_ENABLED = true;
    public static boolean SOUL_STRATIFICATION_EFFECT_ENABLED = true;

    public static boolean ROTTEN_CONSUMPTION_ENABLED = true;

    public static boolean STALKER_IMMUNITY_ENABLED = true;

    public static boolean DECREPIT_SKELETON_SPAWNING_ENABLED = true;

    public static boolean INFESTED_DIAMONDS_ENABLED = true;

    public static boolean NIGHTMARE_SPAWN_ENABLED = true;

    public static int DAYS_TILL_NIGHTMARE = 3;

    public static int DAYS_TILL_MISSIONER = 10;


    public static void bake() {
        try {
             SKELETON_BOMB_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.SKELETON_BOMB_SPAWNING_ENABLED.get();
             DECAYING_ZOMBIE_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.DECAYING_ZOMBIE_SPAWNING_ENABLED.get();
             BABY_SKELETON_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.BABY_SKELETON_SPAWNING_ENABLED.get();
             ZOMBIE_BARREL_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.ZOMBIE_BARREL_SPAWNING_ENABLED.get();
             PHANTOM_CREEPER_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.PHANTOM_CREEPER_SPAWNING_ENABLED.get();
             DOOR_KNIGHT_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.DOOR_KNIGHT_SPAWNING_ENABLED.get();
             RESTLESS_SPIRIT_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.RESTLESS_SPIRIT_SPAWNING_ENABLED.get();
             SKELETON_THRASHER_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.SKELETON_THRASHER_SPAWNING_ENABLED.get();
             FIRELIGHT_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.FIRELIGHT_SPAWNING_ENABLED.get();
             BONES_CALLER_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.BONES_CALLER_SPAWNING_ENABLED.get();
             BONE_IMP_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.BONE_IMP_SPAWNING_ENABLED.get();
             DARK_VORTEX_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.DARK_VORTEX_SPAWNING_ENABLED.get();
             DREADHOUND_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.DREADHOUND_SPAWNING_ENABLED.get();
             FALLEN_CHAOS_KNIGHT_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.FALLEN_CHAOS_KNIGHT_SPAWNING_ENABLED.get();
             SER_PUMPKIN_HEAD_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.SER_PUMPKIN_HEAD_SPAWNING_ENABLED.get();
             ZOMBIE_CLOWN_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.ZOMBIE_CLOWN_SPAWNING_ENABLED.get();
             SPIRIT_GUIDE_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.SPIRIT_GUIDE_SPAWNING_ENABLED.get();

             CORPSE_FLY_SPAWN_ENABLED = ConfigHolder.BORNCONFIG.CORPSE_FLY_SPAWN_ENABLED.get();
             BLOODY_GADFLY_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.BLOODY_GADFLY_SPAWNING_ENABLED.get();
             CORPSE_FISH_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.CORPSE_FISH_SPAWNING_ENABLED.get();
             ZOMBIE_FISHERMAN_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.ZOMBIE_FISHERMAN_SPAWNING_ENABLED.get();
             THORNSHELL_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.THORNSHELL_SPAWNING_ENABLED.get();
             GLUTTON_FISH_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.GLUTTON_FISH_SPAWNING_ENABLED.get();

             ZOMBIE_BRUISER_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.ZOMBIE_BRUISER_SPAWNING_ENABLED.get();
             MAGGOTS_APPEARANCE_ENABLED = ConfigHolder.BORNCONFIG.MAGGOTS_APPEARANCE_ENABLED.get();
             ZOMBIE_LUMBERJACK_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.ZOMBIE_LUMBERJACK_SPAWNING_ENABLED.get();
             MISSIONER_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.MISSIONER_SPAWNING_ENABLED.get();
             FIRE_WELL_GENERATION_ENABLED = ConfigHolder.BORNCONFIG.FIRE_WELL_GENERATION_ENABLED.get();
             OBSERVATION_TOWER_GENERATION_ENABLED = ConfigHolder.BORNCONFIG.OBSERVATION_TOWER_GENERATION_ENABLED.get();
             DARK_TOWER_GENERATION_ENABLED = ConfigHolder.BORNCONFIG.DARK_TOWER_GENERATION_ENABLED.get();
             FARM_GENERATION_ENABLED = ConfigHolder.BORNCONFIG.FARM_GENERATION_ENABLED.get();
             CLOWN_TENT_GENERATION_ENABLED = ConfigHolder.BORNCONFIG.CLOWN_TENT_GENERATION_ENABLED.get();
             SPIRIT_DISSAPPEAR_IN_SUN_ENABLED = ConfigHolder.BORNCONFIG.SPIRIT_DISSAPPEAR_IN_SUN_ENABLED.get();
             SOUL_STRATIFICATION_EFFECT_ENABLED = ConfigHolder.BORNCONFIG.SOUL_STRATIFICATION_EFFECT_ENABLED.get();

             ROTTEN_CONSUMPTION_ENABLED = ConfigHolder.BORNCONFIG.ROTTEN_CONSUMPTION_ENABLED.get();

             STALKER_IMMUNITY_ENABLED = ConfigHolder.BORNCONFIG.STALKER_IMMUNITY_ENABLED.get();

             DECREPIT_SKELETON_SPAWNING_ENABLED = ConfigHolder.BORNCONFIG.DECREPIT_SKELETON_SPAWNING_ENABLED.get();

             INFESTED_DIAMONDS_ENABLED = ConfigHolder.BORNCONFIG.INFESTED_DIAMONDS_ENABLED.get();

             NIGHTMARE_SPAWN_ENABLED = ConfigHolder.BORNCONFIG.NIGHTMARE_SPAWN_ENABLED.get();

             DAYS_TILL_NIGHTMARE = ConfigHolder.BORNCONFIG.DAYS_TILL_NIGHTMARE.get();

             DAYS_TILL_MISSIONER = ConfigHolder.BORNCONFIG.DAYS_TILL_MISSIONER.get();


        } catch (Exception e) {
            LOGGER.warn("An exception was caused trying to load the config for Born In Configuration");
            e.printStackTrace();
        }
    }

}
