package com.crimsoncrips.borninconfiguration.config;

import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraftforge.common.ForgeConfigSpec;

public class BornInChaosConfig {

        public final ForgeConfigSpec.DoubleValue  SUPREME_BONES_CALLER_ARMOR;
        public final ForgeConfigSpec.DoubleValue  SUPREME_BONES_CALLER_DAMAGE;
        public final ForgeConfigSpec.DoubleValue  SUPREME_BONES_CALLER_HEALTH;
        public final ForgeConfigSpec.DoubleValue  SUPREME_BONES_CALLER_KNOCKBACK;
        public final ForgeConfigSpec.DoubleValue  SUPREME_BONES_CALLER_KNOCKBACK_RESISTANCE;
        public final ForgeConfigSpec.DoubleValue INFERNAL_SPIRIT_ARMOR;
        public final ForgeConfigSpec.DoubleValue INFERNAL_SPIRIT_DAMAGE;
        public final ForgeConfigSpec.DoubleValue INFERNAL_SPIRIT_HEALTH;
        public final ForgeConfigSpec.DoubleValue INFERNAL_SPIRIT_KNOCKBACK;
        public final ForgeConfigSpec.DoubleValue INFERNAL_SPIRIT_KNOCKBACK_RESISTANCE;
        public final ForgeConfigSpec.DoubleValue INFERNAL_SPIRIT_SPEED ;
     public final ForgeConfigSpec.DoubleValue  SUPREME_BONES_CALLER_SPEED;
    public final ForgeConfigSpec.BooleanValue BABY_SKELETON_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue BLOODY_GADFLY_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue BONES_CALLER_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue BONE_IMP_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue CORPSE_FISH_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue CORPSE_FLY_SPAWN_ENABLED;
    public final ForgeConfigSpec.BooleanValue DARK_VORTEX_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue DECAYING_ZOMBIE_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue DECREPIT_SKELETON_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue DOOR_KNIGHT_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue DREADHOUND_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue FALLEN_CHAOS_KNIGHT_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue FIRELIGHT_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue GLUTTON_FISH_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue INFESTED_DIAMONDS_ENABLED;
    public final ForgeConfigSpec.BooleanValue LIFESTEALER_SPAWN_ENABLED;
    public final ForgeConfigSpec.BooleanValue MAGGOTS_APPEARANCE_ENABLED;
    public final ForgeConfigSpec.BooleanValue MISSIONER_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue NIGHTMARE_SPAWN_ENABLED;
    public final ForgeConfigSpec.BooleanValue PHANTOM_CREEPER_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue RESTLESS_SPIRIT_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue ROTTEN_CONSUMPTION_ENABLED;
    public final ForgeConfigSpec.BooleanValue SIAMESE_SKELETONS_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue SIR_PUMPKIN_HEAD_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue SKELETON_BOMB_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue SKELETON_THRASHER_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue SOUL_STRATIFICATION_EFFECT_ENABLED;
    public final ForgeConfigSpec.BooleanValue SPIRIT_DISSAPPEAR_IN_SUN_ENABLED;
    public final ForgeConfigSpec.BooleanValue SPIRIT_GUIDE_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue STALKER_IMMUNITY_ENABLED;
    public final ForgeConfigSpec.BooleanValue THORNSHELL_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue ZOMBIE_BARREL_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue ZOMBIE_BRUISER_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue ZOMBIE_CLOWN_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue ZOMBIE_FISHERMAN_SPAWNING_ENABLED;
    public final ForgeConfigSpec.BooleanValue ZOMBIE_LUMBERJACK_SPAWNING_ENABLED;
    public final ForgeConfigSpec.DoubleValue  BLOODY_GADFLY_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  BONES_CALLER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  BONE_IMP_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  BONE_MINION_IMP_ARMOR;
    public final ForgeConfigSpec.DoubleValue  BONE_MINION_IMP_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  BONE_MINION_IMP_HEALTH;
    public final ForgeConfigSpec.DoubleValue  BONE_MINION_IMP_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  BONE_MINION_IMP_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  BONE_MINION_IMP_SPEED;
    public final ForgeConfigSpec.DoubleValue  CORPSE_FISH_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  CORPSE_FISH_SWIM_SPEED;
    public final ForgeConfigSpec.DoubleValue  CORPSE_FLY_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  DARK_VORTEX_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  DIAMOND_TERMITE_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  DOOR_KNIGHT_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_LEADER_ARMOR;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_LEADER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_LEADER_HEALTH;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_LEADER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_LEADER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  DREADHOUND_LEADER_SPEED;
    public final ForgeConfigSpec.DoubleValue  FALLEN_CHAOS_KNIGHT_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  GLUTTON_FISH_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  GLUTTON_FISH_SWIM_SPEED;
    public final ForgeConfigSpec.DoubleValue  LIFESTEALER_ARMOR;
    public final ForgeConfigSpec.DoubleValue  LIFESTEALER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  LIFESTEALER_HEALTH;
    public final ForgeConfigSpec.DoubleValue  LIFESTEALER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  LIFESTEALER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  LIFESTEALER_SPEED;
    public final ForgeConfigSpec.DoubleValue  LORD_PUMPKINHEAD_ARMOR;
    public final ForgeConfigSpec.DoubleValue  LORD_PUMPKINHEAD_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  LORD_PUMPKINHEAD_HEALTH;
    public final ForgeConfigSpec.DoubleValue  LORD_PUMPKINHEAD_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  LORD_PUMPKINHEAD_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  LORD_PUMPKINHEAD_SPEED;
    public final ForgeConfigSpec.DoubleValue  MAGGOT_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  MISSIONER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_ARMOR;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_FLYING_SPEED;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_HEALTH;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  MR_PUMPKIN_SPEED;
    public final ForgeConfigSpec.DoubleValue  NIGHTMARE_STALKER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  PUMPKIN_SPIRIT_ARMOR;
    public final ForgeConfigSpec.DoubleValue  PUMPKIN_SPIRIT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  PUMPKIN_SPIRIT_HEALTH;
    public final ForgeConfigSpec.DoubleValue  PUMPKIN_SPIRIT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  PUMPKIN_SPIRIT_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  PUMPKIN_SPIRIT_SPEED;
    public final ForgeConfigSpec.DoubleValue  RESTLESS_SPIRIT_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_ARMOR;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_FLYING_SPEED;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_HEALTH;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SCARLET_PROSECUTER_SPEED;
    public final ForgeConfigSpec.DoubleValue  SEARED_SPIRIT_ARMOR;
    public final ForgeConfigSpec.DoubleValue  SEARED_SPIRIT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  SEARED_SPIRIT_HEALTH;
    public final ForgeConfigSpec.DoubleValue  SEARED_SPIRIT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  SEARED_SPIRIT_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SEARED_SPIRIT_SPEED;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_ARMOR;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_FLYING_SPEED;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_HEALTH;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SENOR_PUMPKIN_HEAD_SPEED;
    public final ForgeConfigSpec.DoubleValue  SIR_PUMPKIN_HEAD_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SKELETON_THRASHER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SPIRIT_GUIDE_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SPIRIT_OF_CHAOS_ARMOR;
    public final ForgeConfigSpec.DoubleValue  SPIRIT_OF_CHAOS_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  SPIRIT_OF_CHAOS_HEALTH;
    public final ForgeConfigSpec.DoubleValue  SPIRIT_OF_CHAOS_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SPIRIT_OF_CHAOS_SPEED;
    public final ForgeConfigSpec.DoubleValue  SWARMER_ARMOR;
    public final ForgeConfigSpec.DoubleValue  SWARMER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue  SWARMER_HEALTH;
    public final ForgeConfigSpec.DoubleValue  SWARMER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue  SWARMER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  SWARMER_SPEED;
    public final ForgeConfigSpec.DoubleValue  THORNSHELL_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  ZOMBIE_BARREL_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  ZOMBIE_BRUISER_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  ZOMBIE_CLOWN_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  ZOMBIE_FISHERMAN_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue  ZOMBIE_LUMBERJACK_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue BABY_SKELETON_ARMOR;
    public final ForgeConfigSpec.DoubleValue BABY_SKELETON_DAMAGE;
    public final ForgeConfigSpec.DoubleValue BABY_SKELETON_HEALTH;
    public final ForgeConfigSpec.DoubleValue BABY_SKELETON_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue BABY_SKELETON_SPEED;
    public final ForgeConfigSpec.DoubleValue BLOODY_GADFLY_ARMOR;
    public final ForgeConfigSpec.DoubleValue BLOODY_GADFLY_DAMAGE;
    public final ForgeConfigSpec.DoubleValue BLOODY_GADFLY_HEALTH;
    public final ForgeConfigSpec.DoubleValue BLOODY_GADFLY_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue BLOODY_GADFLY_SPEED;
    public final ForgeConfigSpec.DoubleValue BONES_CALLER_ARMOR;
    public final ForgeConfigSpec.DoubleValue BONES_CALLER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue BONES_CALLER_HEALTH;
    public final ForgeConfigSpec.DoubleValue BONES_CALLER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue BONES_CALLER_SPEED;
    public final ForgeConfigSpec.DoubleValue BONE_IMP_ARMOR;
    public final ForgeConfigSpec.DoubleValue BONE_IMP_DAMAGE;
    public final ForgeConfigSpec.DoubleValue BONE_IMP_HEALTH;
    public final ForgeConfigSpec.DoubleValue BONE_IMP_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue BONE_IMP_SPEED;
    public final ForgeConfigSpec.DoubleValue CORPSE_FISH_ARMOR;
    public final ForgeConfigSpec.DoubleValue CORPSE_FISH_DAMAGE;
    public final ForgeConfigSpec.DoubleValue CORPSE_FISH_HEALTH;
    public final ForgeConfigSpec.DoubleValue CORPSE_FISH_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue CORPSE_FISH_SPEED;
    public final ForgeConfigSpec.DoubleValue CORPSE_FLY_ARMOR;
    public final ForgeConfigSpec.DoubleValue CORPSE_FLY_DAMAGE;
    public final ForgeConfigSpec.DoubleValue CORPSE_FLY_HEALTH;
    public final ForgeConfigSpec.DoubleValue CORPSE_FLY_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue CORPSE_FLY_SPEED;
    public final ForgeConfigSpec.DoubleValue DARK_VORTEX_ARMOR;
    public final ForgeConfigSpec.DoubleValue DARK_VORTEX_DAMAGE;
    public final ForgeConfigSpec.DoubleValue DARK_VORTEX_HEALTH;
    public final ForgeConfigSpec.DoubleValue DARK_VORTEX_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue DARK_VORTEX_SPEED;
    public final ForgeConfigSpec.DoubleValue DECAYING_ZOMBIE_ARMOR;
    public final ForgeConfigSpec.DoubleValue DECAYING_ZOMBIE_DAMAGE;
    public final ForgeConfigSpec.DoubleValue DECAYING_ZOMBIE_HEALTH;
    public final ForgeConfigSpec.DoubleValue DECAYING_ZOMBIE_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue DECAYING_ZOMBIE_SPEED;
    public final ForgeConfigSpec.DoubleValue DECREPIT_SKELETON_ARMOR;
    public final ForgeConfigSpec.DoubleValue DECREPIT_SKELETON_DAMAGE;
    public final ForgeConfigSpec.DoubleValue DECREPIT_SKELETON_HEALTH;
    public final ForgeConfigSpec.DoubleValue DECREPIT_SKELETON_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue DECREPIT_SKELETON_SPEED;
    public final ForgeConfigSpec.DoubleValue DIAMOND_TERMITE_ARMOR;
    public final ForgeConfigSpec.DoubleValue DIAMOND_TERMITE_DAMAGE;
    public final ForgeConfigSpec.DoubleValue DIAMOND_TERMITE_HEALTH;
    public final ForgeConfigSpec.DoubleValue DIAMOND_TERMITE_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue DIAMOND_TERMITE_SPEED;
    public final ForgeConfigSpec.DoubleValue DOOR_KNIGHT_ARMOR;
    public final ForgeConfigSpec.DoubleValue DOOR_KNIGHT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue DOOR_KNIGHT_HEALTH;
    public final ForgeConfigSpec.DoubleValue DOOR_KNIGHT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue DOOR_KNIGHT_SPEED;
    public final ForgeConfigSpec.DoubleValue DREADHOUND_ARMOR;
    public final ForgeConfigSpec.DoubleValue DREADHOUND_DAMAGE;
    public final ForgeConfigSpec.DoubleValue DREADHOUND_HEALTH;
    public final ForgeConfigSpec.DoubleValue DREADHOUND_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue DREADHOUND_SPEED;
    public final ForgeConfigSpec.DoubleValue FALLEN_CHAOS_KNIGHT_ARMOR;
    public final ForgeConfigSpec.DoubleValue FALLEN_CHAOS_KNIGHT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue FALLEN_CHAOS_KNIGHT_HEALTH;
    public final ForgeConfigSpec.DoubleValue FALLEN_CHAOS_KNIGHT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue FALLEN_CHAOS_KNIGHT_SPEED;
    public final ForgeConfigSpec.DoubleValue FIRELIGHT_ARMOR;
    public final ForgeConfigSpec.DoubleValue FIRELIGHT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue FIRELIGHT_HEALTH;
    public final ForgeConfigSpec.DoubleValue FIRELIGHT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue FIRELIGHT_SPEED;
    public final ForgeConfigSpec.DoubleValue GLUTTON_FISH_ARMOR;
    public final ForgeConfigSpec.DoubleValue GLUTTON_FISH_DAMAGE;
    public final ForgeConfigSpec.DoubleValue GLUTTON_FISH_HEALTH;
    public final ForgeConfigSpec.DoubleValue GLUTTON_FISH_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue GLUTTON_FISH_SPEED;
    public final ForgeConfigSpec.DoubleValue LORD_HEADLESS_ARMOR;
    public final ForgeConfigSpec.DoubleValue LORD_HEADLESS_DAMAGE;
    public final ForgeConfigSpec.DoubleValue LORD_HEADLESS_HEALTH;
    public final ForgeConfigSpec.DoubleValue LORD_HEADLESS_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue LORD_HEADLESS_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue LORD_HEADLESS_SPEED ;
    public final ForgeConfigSpec.DoubleValue MAGGOT_ARMOR;
    public final ForgeConfigSpec.DoubleValue MAGGOT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue MAGGOT_HEALTH;
    public final ForgeConfigSpec.DoubleValue MAGGOT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue MAGGOT_SPEED;
    public final ForgeConfigSpec.DoubleValue MISSIONER_ARMOR;
    public final ForgeConfigSpec.DoubleValue MISSIONER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue MISSIONER_HEALTH;
    public final ForgeConfigSpec.DoubleValue MISSIONER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue MISSIONER_SPEED;
    public final ForgeConfigSpec.DoubleValue NIGHTMARE_STALKER_ARMOR;
    public final ForgeConfigSpec.DoubleValue NIGHTMARE_STALKER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue NIGHTMARE_STALKER_HEALTH;
    public final ForgeConfigSpec.DoubleValue NIGHTMARE_STALKER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue NIGHTMARE_STALKER_SPEED;
    public final ForgeConfigSpec.DoubleValue PHANTOM_CREEPER_ARMOR;
    public final ForgeConfigSpec.DoubleValue PHANTOM_CREEPER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue PHANTOM_CREEPER_HEALTH;
    public final ForgeConfigSpec.DoubleValue PHANTOM_CREEPER_SPEED;
    public final ForgeConfigSpec.DoubleValue PUMPKINHEAD_ARMOR;
    public final ForgeConfigSpec.DoubleValue PUMPKINHEAD_DAMAGE;
    public final ForgeConfigSpec.DoubleValue PUMPKINHEAD_HEALTH;
    public final ForgeConfigSpec.DoubleValue PUMPKINHEAD_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue PUMPKINHEAD_KNOCKBACK_RESISTANCE;
    public final ForgeConfigSpec.DoubleValue PUMPKINHEAD_SPEED ;
    public final ForgeConfigSpec.DoubleValue RESTLESS_SPIRIT_ARMOR;
    public final ForgeConfigSpec.DoubleValue RESTLESS_SPIRIT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue RESTLESS_SPIRIT_FLYING_SPEED;
    public final ForgeConfigSpec.DoubleValue RESTLESS_SPIRIT_HEALTH;
    public final ForgeConfigSpec.DoubleValue RESTLESS_SPIRIT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue RESTLESS_SPIRIT_SPEED;
    public final ForgeConfigSpec.DoubleValue SIAMESE_SKELETONS_ARMOR;
    public final ForgeConfigSpec.DoubleValue SIAMESE_SKELETONS_DAMAGE;
    public final ForgeConfigSpec.DoubleValue SIAMESE_SKELETONS_HEALTH;
    public final ForgeConfigSpec.DoubleValue SIAMESE_SKELETONS_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue SIAMESE_SKELETONS_SPEED ;
    public final ForgeConfigSpec.DoubleValue SIR_PUMPKIN_HEAD_ARMOR;
    public final ForgeConfigSpec.DoubleValue SIR_PUMPKIN_HEAD_DAMAGE;
    public final ForgeConfigSpec.DoubleValue SIR_PUMPKIN_HEAD_HEALTH;
    public final ForgeConfigSpec.DoubleValue SIR_PUMPKIN_HEAD_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue SIR_PUMPKIN_HEAD_SPEED;
    public final ForgeConfigSpec.DoubleValue SKELETON_BOMBER_ARMOR;
    public final ForgeConfigSpec.DoubleValue SKELETON_BOMBER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue SKELETON_BOMBER_HEALTH;
    public final ForgeConfigSpec.DoubleValue SKELETON_BOMBER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue SKELETON_BOMBER_SPEED;
    public final ForgeConfigSpec.DoubleValue SKELETON_THRASHER_ARMOR;
    public final ForgeConfigSpec.DoubleValue SKELETON_THRASHER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue SKELETON_THRASHER_HEALTH;
    public final ForgeConfigSpec.DoubleValue SKELETON_THRASHER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue SKELETON_THRASHER_SPEED;
    public final ForgeConfigSpec.DoubleValue SPIRIT_ASSISTANT_ARMOR;
    public final ForgeConfigSpec.DoubleValue SPIRIT_ASSISTANT_DAMAGE;
    public final ForgeConfigSpec.DoubleValue SPIRIT_ASSISTANT_HEALTH;
    public final ForgeConfigSpec.DoubleValue SPIRIT_ASSISTANT_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue SPIRIT_ASSISTANT_SPEED ;
    public final ForgeConfigSpec.DoubleValue SPIRIT_GUIDE_ARMOR;
    public final ForgeConfigSpec.DoubleValue SPIRIT_GUIDE_DAMAGE;
    public final ForgeConfigSpec.DoubleValue SPIRIT_GUIDE_HEALTH;
    public final ForgeConfigSpec.DoubleValue SPIRIT_GUIDE_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue SPIRIT_GUIDE_SPEED;
    public final ForgeConfigSpec.DoubleValue THORNSHELL_ARMOR;
    public final ForgeConfigSpec.DoubleValue THORNSHELL_DAMAGE;
    public final ForgeConfigSpec.DoubleValue THORNSHELL_HEALTH;
    public final ForgeConfigSpec.DoubleValue THORNSHELL_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue THORNSHELL_SPEED;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BARREL_ARMOR;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BARREL_DAMAGE;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BARREL_HEALTH;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BARREL_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BARREL_SPEED;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BRUISER_ARMOR;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BRUISER_DAMAGE;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BRUISER_HEALTH;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BRUISER_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_BRUISER_SPEED;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_CLOWN_ARMOR;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_CLOWN_DAMAGE;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_CLOWN_HEALTH;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_CLOWN_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_CLOWN_SPEED;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_FISHERMAN_ARMOR;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_FISHERMAN_DAMAGE;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_FISHERMAN_HEALTH;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_FISHERMAN_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_FISHERMAN_SPEED;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_LUMBERJACK_ARMOR;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_LUMBERJACK_DAMAGE;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_LUMBERJACK_HEALTH;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_LUMBERJACK_KNOCKBACK;
    public final ForgeConfigSpec.DoubleValue ZOMBIE_LUMBERJACK_SPEED;
    public final ForgeConfigSpec.IntValue DAYS_TILL_LIFESTEALER;
    public final ForgeConfigSpec.IntValue DAYS_TILL_MISSIONER;
    public final ForgeConfigSpec.IntValue DAYS_TILL_NIGHTMARE;
    public final ForgeConfigSpec.IntValue SCARLET_SPAWN_AMMOUNT;

    public final ForgeConfigSpec.BooleanValue RETALLIATION_ENABLED;




    public BornInChaosConfig(final ForgeConfigSpec.Builder builder) {

        builder.push("General");
        this.ROTTEN_CONSUMPTION_ENABLED = buildBoolean(builder, "ROTTEN_CONSUMPTION_ENABLED", true, "Whether Rotten Flesh afflicts you with Rotten Stink");
        this.SOUL_STRATIFICATION_EFFECT_ENABLED = buildBoolean(builder, "SOUL_STRATIFICATION_EFFECT_ENABLED", true, "Whether soul stratisfaction is enabled");
        this.SPIRIT_DISSAPPEAR_IN_SUN_ENABLED = buildBoolean(builder, "SPIRIT_DISSAPPEAR_IN_SUN_ENABLED", true, "Whether spirits disappear in the sun is enabled");
        this.RETALLIATION_ENABLED = buildBoolean(builder, "RETALLIATION_ENABLED", true, "Whether mobs retalliate to other mobs attacking them");

        builder.pop();
        builder.push("Baby Skeleton");
        this.BABY_SKELETON_ARMOR = buildDouble(builder, "BABY_SKELETON_ARMOR", 1.0);
        this.BABY_SKELETON_DAMAGE = buildDouble(builder, "BABY_SKELETON_DAMAGE", 2.0);
        this.BABY_SKELETON_HEALTH = buildDouble(builder, "BABY_SKELETON_HEALTH", 10.0);
        this.BABY_SKELETON_KNOCKBACK = buildDouble(builder, "BABY_SKELETON_KNOCKBACK", 0.1);
        this.BABY_SKELETON_SPAWNING_ENABLED = buildBoolean(builder, "BABY_SKELETON_SPAWNING_ENABLED", true, ".");
        this.BABY_SKELETON_SPEED = buildDouble(builder, "BABY_SKELETON_SPEED", 0.3);
        builder.pop();
        builder.push("Bloody Gadfly");
        this.BLOODY_GADFLY_ARMOR = buildDouble(builder, "BLOODY_GADFLY_ARMOR", 0.5);
        this.BLOODY_GADFLY_DAMAGE = buildDouble(builder, "BLOODY_GADFLY_DAMAGE", 3.0);
        this.BLOODY_GADFLY_HEALTH = buildDouble(builder, "BLOODY_GADFLY_HEALTH", 20.0);
        this.BLOODY_GADFLY_KNOCKBACK = buildDouble(builder, "BLOODY_GADFLY_KNOCKBACK", 0.1);
        this.BLOODY_GADFLY_KNOCKBACK_RESISTANCE = buildDouble(builder, "BLOODY_GADFLY_KNOCKBACK_RESISTANCE", 0.4);
        this.BLOODY_GADFLY_SPAWNING_ENABLED = buildBoolean(builder, "BLOODY_GADFLY_SPAWNING_ENABLED", true, ".");
        this.BLOODY_GADFLY_SPEED = buildDouble(builder, "BLOODY_GADFLY_SPEED", 0.28);
        builder.pop();
        builder.push("Bones Caller");
        this.BONES_CALLER_ARMOR = buildDouble(builder, "BONES_CALLER_ARMOR", 1.0);
        this.BONES_CALLER_DAMAGE = buildDouble(builder, "BONES_CALLER_DAMAGE", 3.0);
        this.BONES_CALLER_HEALTH = buildDouble(builder, "BONES_CALLER_HEALTH", 25.0);
        this.BONES_CALLER_KNOCKBACK = buildDouble(builder, "BONES_CALLER_KNOCKBACK", 0.2);
        this.BONES_CALLER_KNOCKBACK_RESISTANCE = buildDouble(builder, "BONES_CALLER_KNOCKBACK_RESISTANCE", 0.2);
        this.BONES_CALLER_SPAWNING_ENABLED = buildBoolean(builder, "BONES_CALLER_SPAWNING_ENABLED", true, ".");
        this.BONES_CALLER_SPEED = buildDouble(builder, "BONES_CALLER_SPEED", 0.2);
        builder.pop();
        builder.push("Bone Imp");
        this.BONE_IMP_ARMOR = buildDouble(builder, "BONE_IMP_ARMOR", 3.5);
        this.BONE_IMP_DAMAGE = buildDouble(builder, "BONE_IMP_DAMAGE", 3.0);
        this.BONE_IMP_HEALTH = buildDouble(builder, "BONE_IMP_HEALTH", 20.0);
        this.BONE_IMP_KNOCKBACK = buildDouble(builder, "BONE_IMP_KNOCKBACK", 1.0);
        this.BONE_IMP_KNOCKBACK_RESISTANCE = buildDouble(builder, "BONE_IMP_KNOCKBACK_RESISTANCE", 0.1);
        this.BONE_IMP_SPAWNING_ENABLED = buildBoolean(builder, "BONE_IMP_SPAWNING_ENABLED", true, ".");
        this.BONE_IMP_SPEED = buildDouble(builder, "BONE_IMP_SPEED", 0.3);
        builder.pop();
        builder.push("Bone Minion Imp");
        this.BONE_MINION_IMP_ARMOR = buildDouble(builder, "BONE_MINION_IMP_ARMOR", 3.5);
        this.BONE_MINION_IMP_DAMAGE = buildDouble(builder, "BONE_MINION_IMP_DAMAGE", 3.0);
        this.BONE_MINION_IMP_HEALTH = buildDouble(builder, "BONE_MINION_IMP_HEALTH", 20.0);
        this.BONE_MINION_IMP_KNOCKBACK = buildDouble(builder, "BONE_MINION_IMP_KNOCKBACK", 1.0);
        this.BONE_MINION_IMP_KNOCKBACK_RESISTANCE = buildDouble(builder, "BONE_MINION_IMP_KNOCKBACK_RESISTANCE", 0.1);
        this.BONE_MINION_IMP_SPEED = buildDouble(builder, "BONE_MINION_IMP_SPEED", 0.3);
        builder.pop();
        builder.push("Corpse Fish");
        this.CORPSE_FISH_ARMOR = buildDouble(builder, "CORPSE_FISH_ARMOR", 0.0);
        this.CORPSE_FISH_DAMAGE = buildDouble(builder, "CORPSE_FISH_DAMAGE", 2.0);
        this.CORPSE_FISH_HEALTH = buildDouble(builder, "CORPSE_FISH_HEALTH", 12.0);
        this.CORPSE_FISH_KNOCKBACK = buildDouble(builder, "CORPSE_FISH_KNOCKBACK", 0.1);
        this.CORPSE_FISH_KNOCKBACK_RESISTANCE = buildDouble(builder, "CORPSE_FISH_KNOCKBACK_RESISTANCE", 0.4);
        this.CORPSE_FISH_SPAWNING_ENABLED = buildBoolean(builder, "CORPSE_FISH_SPAWNING_ENABLED", true, ".");
        this.CORPSE_FISH_SPEED = buildDouble(builder, "CORPSE_FISH_SPEED", 0.7);
        this.CORPSE_FISH_SWIM_SPEED = buildDouble(builder, "CORPSE_FISH_SWIM_SPEED", 0.7);
        builder.pop();
        builder.push("Corpse Fly");
        this.CORPSE_FLY_ARMOR = buildDouble(builder, "CORPSE_FLY_ARMOR", 0.0);
        this.CORPSE_FLY_DAMAGE = buildDouble(builder, "CORPSE_FLY_DAMAGE", 2.0);
        this.CORPSE_FLY_HEALTH = buildDouble(builder, "CORPSE_FLY_HEALTH", 10.0);
        this.CORPSE_FLY_KNOCKBACK = buildDouble(builder, "CORPSE_FLY_KNOCKBACK", 0.1);
        this.CORPSE_FLY_KNOCKBACK_RESISTANCE = buildDouble(builder, "CORPSE_FLY_KNOCKBACK_RESISTANCE", 0.3);
        this.CORPSE_FLY_SPAWN_ENABLED = buildBoolean(builder, "CORPSE_FLY_SPAWN_ENABLED", true, ".");
        this.CORPSE_FLY_SPEED = buildDouble(builder, "CORPSE_FLY_SPEED", 0.29);
        builder.pop();
        builder.push("Dark Vortex");
        this.DARK_VORTEX_ARMOR = buildDouble(builder, "DARK_VORTEX_ARMOR", 0.0);
        this.DARK_VORTEX_DAMAGE = buildDouble(builder, "DARK_VORTEX_DAMAGE", 4.0);
        this.DARK_VORTEX_HEALTH = buildDouble(builder, "DARK_VORTEX_HEALTH", 35.0);
        this.DARK_VORTEX_KNOCKBACK = buildDouble(builder, "DARK_VORTEX_KNOCKBACK", 0.4);
        this.DARK_VORTEX_KNOCKBACK_RESISTANCE = buildDouble(builder, "DARK_VORTEX_KNOCKBACK_RESISTANCE", 0.7);
        this.DARK_VORTEX_SPAWNING_ENABLED = buildBoolean(builder, "DARK_VORTEX_SPAWNING_ENABLED", true, ".");
        this.DARK_VORTEX_SPEED = buildDouble(builder, "DARK_VORTEX_SPEED", 0.3);
        builder.pop();
        builder.push("Decaying Zombie");
        this.DECAYING_ZOMBIE_ARMOR = buildDouble(builder, "DECAYING_ZOMBIE_ARMOR", 0.5);
        this.DECAYING_ZOMBIE_DAMAGE = buildDouble(builder, "DECAYING_ZOMBIE_DAMAGE", 4.0);
        this.DECAYING_ZOMBIE_HEALTH = buildDouble(builder, "DECAYING_ZOMBIE_HEALTH", 30.0);
        this.DECAYING_ZOMBIE_KNOCKBACK = buildDouble(builder, "DECAYING_ZOMBIE_KNOCKBACK", 0.1);
        this.DECAYING_ZOMBIE_SPAWNING_ENABLED = buildBoolean(builder, "DECAYING_ZOMBIE_SPAWNING_ENABLED", true, ".");
        this.DECAYING_ZOMBIE_SPEED = buildDouble(builder, "DECAYING_ZOMBIE_SPEED", 0.2);
        builder.pop();
        builder.push("Decrepit Skeleton");
        this.DECREPIT_SKELETON_ARMOR = buildDouble(builder, "DECREPIT_SKELETON_ARMOR", 1.0);
        this.DECREPIT_SKELETON_DAMAGE = buildDouble(builder, "DECREPIT_SKELETON_DAMAGE", 3.0);
        this.DECREPIT_SKELETON_HEALTH = buildDouble(builder, "DECREPIT_SKELETON_HEALTH", 15.0);
        this.DECREPIT_SKELETON_KNOCKBACK = buildDouble(builder, "DECREPIT_SKELETON_KNOCKBACK", 0.1);
        this.DECREPIT_SKELETON_SPAWNING_ENABLED = buildBoolean(builder, "DECREPIT_SKELETON_SPAWNING_ENABLED", true, ".");
        this.DECREPIT_SKELETON_SPEED = buildDouble(builder, "DECREPIT_SKELETON_SPEED", 0.23);
        builder.pop();
        builder.push("Diamond Thermite");
        this.DIAMOND_TERMITE_ARMOR = buildDouble(builder, "DIAMOND_TERMITE_ARMOR", 7.0);
        this.DIAMOND_TERMITE_DAMAGE = buildDouble(builder, "DIAMOND_TERMITE_DAMAGE", 2.0);
        this.DIAMOND_TERMITE_HEALTH = buildDouble(builder, "DIAMOND_TERMITE_HEALTH", 14.0);
        this.DIAMOND_TERMITE_KNOCKBACK = buildDouble(builder, "DIAMOND_TERMITE_KNOCKBACK", 0.1);
        this.DIAMOND_TERMITE_KNOCKBACK_RESISTANCE = buildDouble(builder, "DIAMOND_TERMITE_KNOCKBACK_RESISTANCE", 0.2);
        this.DIAMOND_TERMITE_SPEED = buildDouble(builder, "DIAMOND_TERMITE_SPEED", 0.3);
        this.INFESTED_DIAMONDS_ENABLED = buildBoolean(builder, "INFESTED_DIAMONDS_ENABLED", true, "Allows Infested Diamonds to spawn");
        builder.pop();
        builder.push("Door Knight");
        this.DOOR_KNIGHT_ARMOR = buildDouble(builder, "DOOR_KNIGHT_ARMOR", 7.0);
        this.DOOR_KNIGHT_DAMAGE = buildDouble(builder, "DOOR_KNIGHT_DAMAGE", 6.0);
        this.DOOR_KNIGHT_HEALTH = buildDouble(builder, "DOOR_KNIGHT_HEALTH", 30.0);
        this.DOOR_KNIGHT_KNOCKBACK = buildDouble(builder, "DOOR_KNIGHT_KNOCKBACK", 0.5);
        this.DOOR_KNIGHT_KNOCKBACK_RESISTANCE = buildDouble(builder, "DOOR_KNIGHT_KNOCKBACK_RESISTANCE", 0.3);
        this.DOOR_KNIGHT_SPAWNING_ENABLED = buildBoolean(builder, "DOOR_KNIGHT_SPAWNING_ENABLED", true, ".");
        this.DOOR_KNIGHT_SPEED = buildDouble(builder, "DOOR_KNIGHT_SPEED", 0.21);
        builder.pop();
        builder.push("Dreadhound");
        this.DREADHOUND_ARMOR = buildDouble(builder, "DREADHOUND_ARMOR", 0.5);
        this.DREADHOUND_DAMAGE = buildDouble(builder, "DREADHOUND_DAMAGE", 5.0);
        this.DREADHOUND_HEALTH = buildDouble(builder, "DREADHOUND_HEALTH", 17.0);
        this.DREADHOUND_KNOCKBACK = buildDouble(builder, "DREADHOUND_KNOCKBACK", 0.1);
        this.DREADHOUND_KNOCKBACK_RESISTANCE = buildDouble(builder, "DREADHOUND_KNOCKBACK_RESISTANCE", 0.1);
        this.DREADHOUND_SPAWNING_ENABLED = buildBoolean(builder, "DREADHOUND_SPAWNING_ENABLED", true, ".");
        this.DREADHOUND_SPEED = buildDouble(builder, "DREADHOUND_SPEED", 0.34);
        builder.pop();
        builder.push("Dreadhound Leader");
        this.DREADHOUND_LEADER_ARMOR = buildDouble(builder, "DREADHOUND_LEADER_ARMOR", 0.5);
        this.DREADHOUND_LEADER_DAMAGE = buildDouble(builder, "DREADHOUND_LEADER_DAMAGE", 10.0);
        this.DREADHOUND_LEADER_HEALTH = buildDouble(builder, "DREADHOUND_LEADER_HEALTH", 100.0);
        this.DREADHOUND_LEADER_KNOCKBACK = buildDouble(builder, "DREADHOUND_LEADER_KNOCKBACK", 1.4);
        this.DREADHOUND_LEADER_KNOCKBACK_RESISTANCE = buildDouble(builder, "DREADHOUND_LEADER_KNOCKBACK_RESISTANCE", 0.7);
        this.DREADHOUND_LEADER_SPEED = buildDouble(builder, "DREADHOUND_LEADER_SPEED", 0.34);
        builder.pop();
        builder.push("Fallen Chaos Knight");
        this.FALLEN_CHAOS_KNIGHT_ARMOR = buildDouble(builder, "FALLEN_CHAOS_KNIGHT_ARMOR", 20.0);
        this.FALLEN_CHAOS_KNIGHT_DAMAGE = buildDouble(builder, "FALLEN_CHAOS_KNIGHT_DAMAGE", 5.0);
        this.FALLEN_CHAOS_KNIGHT_HEALTH = buildDouble(builder, "FALLEN_CHAOS_KNIGHT_HEALTH", 40.0);
        this.FALLEN_CHAOS_KNIGHT_KNOCKBACK = buildDouble(builder, "FALLEN_CHAOS_KNIGHT_KNOCKBACK", 0.1);
        this.FALLEN_CHAOS_KNIGHT_KNOCKBACK_RESISTANCE = buildDouble(builder, "FALLEN_CHAOS_KNIGHT_KNOCKBACK_RESISTANCE", 0.7);
        this.FALLEN_CHAOS_KNIGHT_SPAWNING_ENABLED = buildBoolean(builder, "FALLEN_CHAOS_KNIGHT_SPAWNING_ENABLED", true, ".");
        this.FALLEN_CHAOS_KNIGHT_SPEED = buildDouble(builder, "FALLEN_CHAOS_KNIGHT_SPEED", 0.32);
        builder.pop();
        builder.push("Firelight");
        this.FIRELIGHT_ARMOR = buildDouble(builder, "FIRELIGHT_ARMOR", 0.0);
        this.FIRELIGHT_DAMAGE = buildDouble(builder, "FIRELIGHT_DAMAGE", 2.0);
        this.FIRELIGHT_HEALTH = buildDouble(builder, "FIRELIGHT_HEALTH", 15.0);
        this.FIRELIGHT_KNOCKBACK = buildDouble(builder, "FIRELIGHT_KNOCKBACK", 0.1);
        this.FIRELIGHT_SPAWNING_ENABLED = buildBoolean(builder, "FIRELIGHT_SPAWNING_ENABLED", true, ".");
        this.FIRELIGHT_SPEED = buildDouble(builder, "FIRELIGHT_SPEED", 0.3);
        builder.pop();
        builder.push("Glutton Fish");
        this.GLUTTON_FISH_ARMOR = buildDouble(builder, "GLUTTON_FISH_ARMOR", 3.0);
        this.GLUTTON_FISH_DAMAGE = buildDouble(builder, "GLUTTON_FISH_DAMAGE", 12.0);
        this.GLUTTON_FISH_HEALTH = buildDouble(builder, "GLUTTON_FISH_HEALTH", 90.0);
        this.GLUTTON_FISH_KNOCKBACK = buildDouble(builder, "GLUTTON_FISH_KNOCKBACK", 0.9);
        this.GLUTTON_FISH_KNOCKBACK_RESISTANCE = buildDouble(builder, "GLUTTON_FISH_KNOCKBACK_RESISTANCE", 0.5);
        this.GLUTTON_FISH_SPAWNING_ENABLED = buildBoolean(builder, "GLUTTON_FISH_SPAWNING_ENABLED", true, ".");
        this.GLUTTON_FISH_SPEED = buildDouble(builder, "GLUTTON_FISH_SPEED", 0.7);
        this.GLUTTON_FISH_SWIM_SPEED = buildDouble(builder, "GLUTTON_FISH_SWIM_SPEED", 0.7);
        builder.pop();
        builder.push("Infernal Spirit");
        this.INFERNAL_SPIRIT_ARMOR = buildDouble(builder, "INFERNAL_SPIRIT_ARMOR", 0.22);
        this.INFERNAL_SPIRIT_DAMAGE = buildDouble(builder, "INFERNAL_SPIRIT_DAMAGE", 16.0);
        this.INFERNAL_SPIRIT_HEALTH = buildDouble(builder, "INFERNAL_SPIRIT_HEALTH", 90.0);
        this.INFERNAL_SPIRIT_KNOCKBACK = buildDouble(builder, "INFERNAL_SPIRIT_KNOCKBACK", 2.3);
        this.INFERNAL_SPIRIT_KNOCKBACK_RESISTANCE = buildDouble(builder, "INFERNAL_SPIRIT_KNOCKBACK_RESISTANCE", 0.9);
        this.INFERNAL_SPIRIT_SPEED = buildDouble(builder, "INFERNAL_SPIRIT_SPEED", 12.0);
        builder.pop();
        builder.push("Lifestealer");
        this.DAYS_TILL_LIFESTEALER = buildInt(builder, "DAYS_TILL_LIFESTEALER", 10, 1,999999,"Days till Lifestealer spawns");
        this.LIFESTEALER_ARMOR = buildDouble(builder, "LIFESTEALER_ARMOR", 16.0);
        this.LIFESTEALER_DAMAGE = buildDouble(builder, "LIFESTEALER_DAMAGE", 7.0);
        this.LIFESTEALER_HEALTH = buildDouble(builder, "LIFESTEALER_HEALTH", 100.0);
        this.LIFESTEALER_KNOCKBACK = buildDouble(builder, "LIFESTEALER_KNOCKBACK", 1.5);
        this.LIFESTEALER_KNOCKBACK_RESISTANCE = buildDouble(builder, "LIFESTEALER_KNOCKBACK_RESISTANCE", 0.9);
        this.LIFESTEALER_SPAWN_ENABLED = buildBoolean(builder, "LIFESTEALER_SPAWN_ENABLED", true, ".");
        this.LIFESTEALER_SPEED = buildDouble(builder, "LIFESTEALER_SPEED", 0.26);
        builder.pop();
        builder.push("Lord Headless");
        this.LORD_HEADLESS_ARMOR = buildDouble(builder, "LORD_HEADLESS_ARMOR", 12.0);
        this.LORD_HEADLESS_DAMAGE = buildDouble(builder, "LORD_HEADLESS_DAMAGE", 12.0);
        this.LORD_HEADLESS_HEALTH = buildDouble(builder, "LORD_HEADLESS_HEALTH", 200.0);
        this.LORD_HEADLESS_KNOCKBACK = buildDouble(builder, "LORD_HEADLESS_KNOCKBACK", 2.3);
        this.LORD_HEADLESS_KNOCKBACK_RESISTANCE = buildDouble(builder, "LORD_HEADLESS_KNOCKBACK_RESISTANCE", 0.9);
        this.LORD_HEADLESS_SPEED = buildDouble(builder, "LORD_HEADLESS_SPEED", 0.3);
        builder.pop();
        builder.push("Lord Pumpkinhead");
        this.LORD_PUMPKINHEAD_ARMOR = buildDouble(builder, "LORD_PUMPKINHEAD_ARMOR", 12.0);
        this.LORD_PUMPKINHEAD_DAMAGE = buildDouble(builder, "LORD_PUMPKINHEAD_DAMAGE", 12.0);
        this.LORD_PUMPKINHEAD_HEALTH = buildDouble(builder, "LORD_PUMPKINHEAD_HEALTH", 600.0);
        this.LORD_PUMPKINHEAD_KNOCKBACK = buildDouble(builder, "LORD_PUMPKINHEAD_KNOCKBACK", 1.3);
        this.LORD_PUMPKINHEAD_KNOCKBACK_RESISTANCE = buildDouble(builder, "LORD_PUMPKINHEAD_KNOCKBACK_RESISTANCE", 0.9);
        this.LORD_PUMPKINHEAD_SPEED = buildDouble(builder, "LORD_PUMPKINHEAD_SPEED", 0.36);
        builder.pop();
        builder.push("Maggots");
        this.MAGGOTS_APPEARANCE_ENABLED = buildBoolean(builder, "MAGGOTS_APPEARANCE_ENABLED", true, "Whether maggots appearing is enabled");
        this.MAGGOT_ARMOR = buildDouble(builder, "MAGGOT_ARMOR", 0.0);
        this.MAGGOT_DAMAGE = buildDouble(builder, "MAGGOT_DAMAGE", 1.0);
        this.MAGGOT_HEALTH = buildDouble(builder, "MAGGOT_HEALTH", 6.0);
        this.MAGGOT_KNOCKBACK = buildDouble(builder, "MAGGOT_KNOCKBACK", 1);
        this.MAGGOT_KNOCKBACK_RESISTANCE = buildDouble(builder, "MAGGOT_KNOCKBACK_RESISTANCE", 0.2);
        this.MAGGOT_SPEED = buildDouble(builder, "MAGGOT_SPEED", 0.2);
        builder.pop();
        builder.push("Missioner");
        this.DAYS_TILL_MISSIONER = buildInt(builder, "DAYS_TILL_MISSIONER", 10, 1,999999,"Days till The Missioner spawns");
        this.MISSIONER_ARMOR = buildDouble(builder, "MISSIONER_ARMOR", 10.0);
        this.MISSIONER_DAMAGE = buildDouble(builder, "MISSIONER_DAMAGE", 9.0);
        this.MISSIONER_HEALTH = buildDouble(builder, "MISSIONER_HEALTH", 150.0);
        this.MISSIONER_KNOCKBACK = buildDouble(builder, "MISSIONER_KNOCKBACK", 1.0);
        this.MISSIONER_KNOCKBACK_RESISTANCE = buildDouble(builder, "MISSIONER_KNOCKBACK_RESISTANCE", 1.0);
        this.MISSIONER_SPAWNING_ENABLED = buildBoolean(builder, "MISSIONER_SPAWNING_ENABLED", true, ".");
        this.MISSIONER_SPEED = buildDouble(builder, "MISSIONER_SPEED", 0.24);
        builder.pop();
        builder.push("Mr Pumpkinhead");
        this.MR_PUMPKIN_ARMOR = buildDouble(builder, "MR_PUMPKIN_ARMOR", 0.0);
        this.MR_PUMPKIN_DAMAGE = buildDouble(builder, "MR_PUMPKIN_DAMAGE", 3.0);
        this.MR_PUMPKIN_FLYING_SPEED = buildDouble(builder, "MR_PUMPKIN_FLYING_SPEED", 0.35);
        this.MR_PUMPKIN_HEALTH = buildDouble(builder, "MR_PUMPKIN_HEALTH", 12.0);
        this.MR_PUMPKIN_KNOCKBACK = buildDouble(builder, "MR_PUMPKIN_KNOCKBACK", 0.3);
        this.MR_PUMPKIN_KNOCKBACK_RESISTANCE = buildDouble(builder, "MR_PUMPKIN_KNOCKBACK_RESISTANCE", 0.9);
        this.MR_PUMPKIN_SPEED = buildDouble(builder, "MR_PUMPKIN_SPEED", 0.35);
        builder.pop();
        builder.push("Nightmare Stalker");
        this.DAYS_TILL_NIGHTMARE = buildInt(builder, "DAYS_TILL_NIGHTMARE", 3, 1,999999,"Days till Nightmare Stalker spawns");
        this.STALKER_IMMUNITY_ENABLED = buildBoolean(builder, "STALKER_IMMUNITY_ENABLED", true, "Whether Nightmare Stalker has its base immunity to certain things");
        this.NIGHTMARE_SPAWN_ENABLED = buildBoolean(builder, "NIGHTMARE_SPAWN_ENABLED", true, ".");
        this.NIGHTMARE_STALKER_ARMOR = buildDouble(builder, "NIGHTMARE_STALKER_ARMOR", 4.0);
        this.NIGHTMARE_STALKER_DAMAGE = buildDouble(builder, "NIGHTMARE_STALKER_DAMAGE", 7.0);
        this.NIGHTMARE_STALKER_HEALTH = buildDouble(builder, "NIGHTMARE_STALKER_HEALTH", 70.0);
        this.NIGHTMARE_STALKER_KNOCKBACK = buildDouble(builder, "NIGHTMARE_STALKER_KNOCKBACK", 1.7);
        this.NIGHTMARE_STALKER_KNOCKBACK_RESISTANCE = buildDouble(builder, "NIGHTMARE_STALKER_KNOCKBACK_RESISTANCE", 0.8);
        this.NIGHTMARE_STALKER_SPEED = buildDouble(builder, "NIGHTMARE_STALKER_SPEED", 0.28);
        builder.pop();
        builder.push("Phantom Creeper");
        this.PHANTOM_CREEPER_ARMOR = buildDouble(builder, "PHANTOM_CREEPER_ARMOR", 0.0);
        this.PHANTOM_CREEPER_DAMAGE = buildDouble(builder, "PHANTOM_CREEPER_DAMAGE", 3.0);
        this.PHANTOM_CREEPER_HEALTH = buildDouble(builder, "PHANTOM_CREEPER_HEALTH", 20.0);
        this.PHANTOM_CREEPER_SPAWNING_ENABLED = buildBoolean(builder, "PHANTOM_CREEPER_SPAWNING_ENABLED", true, ".");
        this.PHANTOM_CREEPER_SPEED = buildDouble(builder, "PHANTOM_CREEPER_SPEED", 0.25);
        builder.pop();
        builder.push("Pumpkinhead");
        this.PUMPKINHEAD_ARMOR = buildDouble(builder, "PUMPKINHEAD_ARMOR", 4.0);
        this.PUMPKINHEAD_DAMAGE = buildDouble(builder, "PUMPKINHEAD_DAMAGE", 3.0);
        this.PUMPKINHEAD_HEALTH = buildDouble(builder, "PUMPKINHEAD_HEALTH", 65.0);
        this.PUMPKINHEAD_KNOCKBACK = buildDouble(builder, "PUMPKINHEAD_KNOCKBACK", 0.3);
        this.PUMPKINHEAD_KNOCKBACK_RESISTANCE = buildDouble(builder, "PUMPKINHEAD_KNOCKBACK_RESISTANCE", 0.6);
        this.PUMPKINHEAD_SPEED = buildDouble(builder, "PUMPKINHEAD_SPEED", 0.32);
        builder.pop();
        builder.push("Pumpkin Spirit");
        this.PUMPKIN_SPIRIT_ARMOR = buildDouble(builder, "PUMPKIN_SPIRIT_ARMOR", 12.0);
        this.PUMPKIN_SPIRIT_DAMAGE = buildDouble(builder, "PUMPKIN_SPIRIT_DAMAGE", 13.0);
        this.PUMPKIN_SPIRIT_HEALTH = buildDouble(builder, "PUMPKIN_SPIRIT_HEALTH", 66.0);
        this.PUMPKIN_SPIRIT_KNOCKBACK = buildDouble(builder, "PUMPKIN_SPIRIT_KNOCKBACK", 2.0);
        this.PUMPKIN_SPIRIT_KNOCKBACK_RESISTANCE = buildDouble(builder, "PUMPKIN_SPIRIT_KNOCKBACK_RESISTANCE", 0.9);
        this.PUMPKIN_SPIRIT_SPEED = buildDouble(builder, "PUMPKIN_SPIRIT_SPEED", 0.22);
        builder.pop();
        builder.push("Restless Spirit");
        this.RESTLESS_SPIRIT_ARMOR = buildDouble(builder, "RESTLESS_SPIRIT_ARMOR", 0.0);
        this.RESTLESS_SPIRIT_DAMAGE = buildDouble(builder, "RESTLESS_SPIRIT_DAMAGE", 2.0);
        this.RESTLESS_SPIRIT_FLYING_SPEED = buildDouble(builder, "RESTLESS_SPIRIT_FLYING_SPEED", 0.4);
        this.RESTLESS_SPIRIT_HEALTH = buildDouble(builder, "RESTLESS_SPIRIT_HEALTH", 24.0);
        this.RESTLESS_SPIRIT_KNOCKBACK = buildDouble(builder, "RESTLESS_SPIRIT_KNOCKBACK", 0.1);
        this.RESTLESS_SPIRIT_KNOCKBACK_RESISTANCE = buildDouble(builder, "RESTLESS_SPIRIT_KNOCKBACK_RESISTANCE", 1.0);
        this.RESTLESS_SPIRIT_SPAWNING_ENABLED = buildBoolean(builder, "RESTLESS_SPIRIT_SPAWNING_ENABLED", true, ".");
        this.RESTLESS_SPIRIT_SPEED = buildDouble(builder, "RESTLESS_SPIRIT_SPEED", 0.4);
        builder.pop();
        builder.push("Scarlet Prosecuter");
        this.SCARLET_SPAWN_AMMOUNT = buildInt(builder, "SCARLET_SPAWN_AMMOUNT", 5, 0,1000,"Amount of Scarlet Prosecuters (setting it to 0 will cause non to spawn)");
        this.SCARLET_PROSECUTER_ARMOR = buildDouble(builder, "SCARLET_PROSECUTER_ARMOR", 0.0);
        this.SCARLET_PROSECUTER_DAMAGE = buildDouble(builder, "SCARLET_PROSECUTER_DAMAGE", 5.0);
        this.SCARLET_PROSECUTER_FLYING_SPEED = buildDouble(builder, "SCARLET_PROSECUTER_FLYING_SPEED", 0.6);
        this.SCARLET_PROSECUTER_HEALTH = buildDouble(builder, "SCARLET_PROSECUTER_HEALTH", 35.0);
        this.SCARLET_PROSECUTER_KNOCKBACK = buildDouble(builder, "SCARLET_PROSECUTER_KNOCKBACK", 0.5);
        this.SCARLET_PROSECUTER_KNOCKBACK_RESISTANCE = buildDouble(builder, "SCARLET_PROSECUTER_KNOCKBACK_RESISTANCE", 0.9);
        this.SCARLET_PROSECUTER_SPEED = buildDouble(builder, "SCARLET_PROSECUTER_SPEED", 0.6);
        builder.pop();
        builder.push("Seared Spirit");
        this.SEARED_SPIRIT_ARMOR = buildDouble(builder, "SEARED_SPIRIT_ARMOR", 3.0);
        this.SEARED_SPIRIT_DAMAGE = buildDouble(builder, "SEARED_SPIRIT_DAMAGE", 10.0);
        this.SEARED_SPIRIT_HEALTH = buildDouble(builder, "SEARED_SPIRIT_HEALTH", 50.0);
        this.SEARED_SPIRIT_KNOCKBACK = buildDouble(builder, "SEARED_SPIRIT_KNOCKBACK", 2.0);
        this.SEARED_SPIRIT_KNOCKBACK_RESISTANCE = buildDouble(builder, "SEARED_SPIRIT_KNOCKBACK_RESISTANCE", 0.3);
        this.SEARED_SPIRIT_SPEED = buildDouble(builder, "SEARED_SPIRIT_SPEED", 0.23);
        builder.pop();
        builder.push("Senor Pumpkinhead");
        this.SENOR_PUMPKIN_HEAD_ARMOR = buildDouble(builder, "SENOR_PUMPKIN_HEAD_ARMOR", 2.0);
        this.SENOR_PUMPKIN_HEAD_DAMAGE = buildDouble(builder, "SENOR_PUMPKIN_HEAD_DAMAGE", 5.0);
        this.SENOR_PUMPKIN_HEAD_FLYING_SPEED = buildDouble(builder, "SENOR_PUMPKIN_HEAD_FLYING_SPEED", 0.5);
        this.SENOR_PUMPKIN_HEAD_HEALTH = buildDouble(builder, "SENOR_PUMPKIN_HEAD_HEALTH", 35.0);
        this.SENOR_PUMPKIN_HEAD_KNOCKBACK = buildDouble(builder, "SENOR_PUMPKIN_HEAD_KNOCKBACK", 1.0);
        this.SENOR_PUMPKIN_HEAD_KNOCKBACK_RESISTANCE = buildDouble(builder, "SENOR_PUMPKIN_HEAD_KNOCKBACK_RESISTANCE", 0.9);
        this.SENOR_PUMPKIN_HEAD_SPEED = buildDouble(builder, "SENOR_PUMPKIN_HEAD_SPEED", 0.5);
        builder.pop();
        builder.push("Sir Pumpkinhead");
        this.SIR_PUMPKIN_HEAD_ARMOR = buildDouble(builder, "SIR_PUMPKIN_HEAD_ARMOR", 9.0);
        this.SIR_PUMPKIN_HEAD_DAMAGE = buildDouble(builder, "SIR_PUMPKIN_HEAD_DAMAGE", 6.0);
        this.SIR_PUMPKIN_HEAD_HEALTH = buildDouble(builder, "SIR_PUMPKIN_HEAD_HEALTH", 160.0);
        this.SIR_PUMPKIN_HEAD_KNOCKBACK = buildDouble(builder, "SIR_PUMPKIN_HEAD_KNOCKBACK", 1.2);
        this.SIR_PUMPKIN_HEAD_KNOCKBACK_RESISTANCE = buildDouble(builder, "SIR_PUMPKIN_HEAD_KNOCKBACK_RESISTANCE", 0.9);
        this.SIR_PUMPKIN_HEAD_SPAWNING_ENABLED = buildBoolean(builder, "SIR_PUMPKIN_HEAD_SPAWNING_ENABLED", true, ".");
        this.SIR_PUMPKIN_HEAD_SPEED = buildDouble(builder, "SIR_PUMPKIN_HEAD_SPEED", 0.36);
        builder.pop();
        builder.push("Siamese Skeletons");
        this.SIAMESE_SKELETONS_ARMOR = buildDouble(builder, "SIAMESE_SKELETONS_ARMOR", 2.0);
        this.SIAMESE_SKELETONS_DAMAGE = buildDouble(builder, "SIAMESE_SKELETONS_DAMAGE", 3.0);
        this.SIAMESE_SKELETONS_HEALTH = buildDouble(builder, "SIAMESE_SKELETONS_HEALTH", 20.0);
        this.SIAMESE_SKELETONS_KNOCKBACK = buildDouble(builder, "SIAMESE_SKELETONS_KNOCKBACK", 0.1);
        this.SIAMESE_SKELETONS_SPAWNING_ENABLED = buildBoolean(builder, "SIAMESE_SKELETONS_SPAWNING_ENABLED", true, ".");
        this.SIAMESE_SKELETONS_SPEED = buildDouble(builder, "SIAMESE_SKELETONS_SPEED", 0.3);
        builder.pop();
        builder.push("Skeleton Demoman");
        this.SKELETON_BOMBER_ARMOR = buildDouble(builder, "SKELETON_BOMBER_ARMOR", 0.5);
        this.SKELETON_BOMBER_DAMAGE = buildDouble(builder, "SKELETON_BOMBER_DAMAGE", 3);
        this.SKELETON_BOMBER_HEALTH = buildDouble(builder, "SKELETON_BOMBER_HEALTH", 25);
        this.SKELETON_BOMBER_KNOCKBACK = buildDouble(builder, "SKELETON_BOMBER_KNOCKBACK", 0.1);
        this.SKELETON_BOMBER_SPEED = buildDouble(builder, "SKELETON_BOMBER_SPEED", 0.22);
        this.SKELETON_BOMB_SPAWNING_ENABLED = buildBoolean(builder, "SKELETON_BOMB_SPAWNING_ENABLED", true, ".");
        builder.pop();
        builder.push("Skeleton Thrasher");
        this.SKELETON_THRASHER_ARMOR = buildDouble(builder, "SKELETON_THRASHER_ARMOR", 7.0);
        this.SKELETON_THRASHER_DAMAGE = buildDouble(builder, "SKELETON_THRASHER_DAMAGE", 8.0);
        this.SKELETON_THRASHER_HEALTH = buildDouble(builder, "SKELETON_THRASHER_HEALTH", 50.0);
        this.SKELETON_THRASHER_KNOCKBACK = buildDouble(builder, "SKELETON_THRASHER_KNOCKBACK", 4.4);
        this.SKELETON_THRASHER_KNOCKBACK_RESISTANCE = buildDouble(builder, "SKELETON_THRASHER_KNOCKBACK_RESISTANCE", 1.0);
        this.SKELETON_THRASHER_SPAWNING_ENABLED = buildBoolean(builder, "SKELETON_THRASHER_SPAWNING_ENABLED", true, ".");
        this.SKELETON_THRASHER_SPEED = buildDouble(builder, "SKELETON_THRASHER_SPEED", 0.21);
        builder.pop();
        builder.push("Spirit Assitant");
        this.SPIRIT_ASSISTANT_ARMOR = buildDouble(builder, "SPIRIT_ASSISTANT_ARMOR", 1.0);
        this.SPIRIT_ASSISTANT_DAMAGE = buildDouble(builder, "SPIRIT_ASSISTANT_DAMAGE", 2.0);
        this.SPIRIT_ASSISTANT_HEALTH = buildDouble(builder, "SPIRIT_ASSISTANT_HEALTH", 15.0);
        this.SPIRIT_ASSISTANT_KNOCKBACK = buildDouble(builder, "SPIRIT_ASSISTANT_KNOCKBACK", 0.1);
        this.SPIRIT_ASSISTANT_SPEED = buildDouble(builder, "SPIRIT_ASSISTANT_SPEED", 0.3);
        builder.pop();
        builder.push("Spirit Guide");
        this.SPIRIT_GUIDE_ARMOR = buildDouble(builder, "SPIRIT_GUIDE_ARMOR", 2.0);
        this.SPIRIT_GUIDE_DAMAGE = buildDouble(builder, "SPIRIT_GUIDE_DAMAGE", 3.0);
        this.SPIRIT_GUIDE_HEALTH = buildDouble(builder, "SPIRIT_GUIDE_HEALTH", 32.0);
        this.SPIRIT_GUIDE_KNOCKBACK = buildDouble(builder, "SPIRIT_GUIDE_KNOCKBACK", 0.9);
        this.SPIRIT_GUIDE_KNOCKBACK_RESISTANCE = buildDouble(builder, "SPIRIT_GUIDE_KNOCKBACK_RESISTANCE", 0.2);
        this.SPIRIT_GUIDE_SPAWNING_ENABLED = buildBoolean(builder, "SPIRIT_GUIDE_SPAWNING_ENABLED", true, ".");
        this.SPIRIT_GUIDE_SPEED = buildDouble(builder, "SPIRIT_GUIDE_SPEED", 0.22);
        builder.pop();
        builder.push("Spirit Of Chaos");
        this.SPIRIT_OF_CHAOS_ARMOR = buildDouble(builder, "SPIRIT_OF_CHAOS_ARMOR", 0.0);
        this.SPIRIT_OF_CHAOS_DAMAGE = buildDouble(builder, "SPIRIT_OF_CHAOS_DAMAGE", 3.0);
        this.SPIRIT_OF_CHAOS_HEALTH = buildDouble(builder, "SPIRIT_OF_CHAOS_HEALTH", 15.0);
        this.SPIRIT_OF_CHAOS_KNOCKBACK_RESISTANCE = buildDouble(builder, "SPIRIT_OF_CHAOS_KNOCKBACK_RESISTANCE", 0.6);
        this.SPIRIT_OF_CHAOS_SPEED = buildDouble(builder, "SPIRIT_OF_CHAOS_SPEED", 0.3);
        builder.pop();
        builder.push("Supreme Bones Caller");
        this.SUPREME_BONES_CALLER_ARMOR = buildDouble(builder, "SUPREME_BONES_CALLER_ARMOR", 5.0);
        this.SUPREME_BONES_CALLER_DAMAGE = buildDouble(builder, "SUPREME_BONES_CALLER_DAMAGE", 5.0);
        this.SUPREME_BONES_CALLER_HEALTH = buildDouble(builder, "SUPREME_BONES_CALLER_HEALTH", 65.0);
        this.SUPREME_BONES_CALLER_KNOCKBACK = buildDouble(builder, "SUPREME_BONES_CALLER_KNOCKBACK", 0.2);
        this.SUPREME_BONES_CALLER_KNOCKBACK_RESISTANCE = buildDouble(builder, "SUPREME_BONES_CALLER_KNOCKBACK_RESISTANCE", 0.5);
        this.SUPREME_BONES_CALLER_SPEED = buildDouble(builder, "SUPREME_BONES_CALLER_SPEED", 0.2);
        builder.pop();
        builder.push("Swarmer");
        this.SWARMER_ARMOR = buildDouble(builder, "SWARMER_ARMOR", 4.0);
        this.SWARMER_DAMAGE = buildDouble(builder, "SWARMER_DAMAGE", 4.0);
        this.SWARMER_HEALTH = buildDouble(builder, "SWARMER_HEALTH", 40.0);
        this.SWARMER_KNOCKBACK = buildDouble(builder, "SWARMER_KNOCKBACK", 0.1);
        this.SWARMER_KNOCKBACK_RESISTANCE = buildDouble(builder, "SWARMER_KNOCKBACK_RESISTANCE", 0.5);
        this.SWARMER_SPEED = buildDouble(builder, "SWARMER_SPEED", 0.2);
        builder.pop();
        builder.push("Thornshell");
        this.THORNSHELL_ARMOR = buildDouble(builder, "THORNSHELL_ARMOR", 10.0);
        this.THORNSHELL_DAMAGE = buildDouble(builder, "THORNSHELL_DAMAGE", 4.0);
        this.THORNSHELL_HEALTH = buildDouble(builder, "THORNSHELL_HEALTH", 25.0);
        this.THORNSHELL_KNOCKBACK = buildDouble(builder, "THORNSHELL_KNOCKBACK", 0.7);
        this.THORNSHELL_KNOCKBACK_RESISTANCE = buildDouble(builder, "THORNSHELL_KNOCKBACK_RESISTANCE", 0.8);
        this.THORNSHELL_SPAWNING_ENABLED = buildBoolean(builder, "THORNSHELL_SPAWNING_ENABLED", true, ".");
        this.THORNSHELL_SPEED = buildDouble(builder, "THORNSHELL_SPEED", 0.25);
        builder.pop();
        builder.push("Zombie Barrel");
        this.ZOMBIE_BARREL_ARMOR = buildDouble(builder, "ZOMBIE_BARREL_ARMOR", 6.0);
        this.ZOMBIE_BARREL_DAMAGE = buildDouble(builder, "ZOMBIE_BARREL_DAMAGE", 3.0);
        this.ZOMBIE_BARREL_HEALTH = buildDouble(builder, "ZOMBIE_BARREL_HEALTH", 30.0);
        this.ZOMBIE_BARREL_KNOCKBACK = buildDouble(builder, "ZOMBIE_BARREL_KNOCKBACK", 0.1);
        this.ZOMBIE_BARREL_KNOCKBACK_RESISTANCE = buildDouble(builder, "ZOMBIE_BARREL_KNOCKBACK_RESISTANCE", 0.1);
        this.ZOMBIE_BARREL_SPAWNING_ENABLED = buildBoolean(builder, "ZOMBIE_BARREL_SPAWNING_ENABLED", true, ".");
        this.ZOMBIE_BARREL_SPEED = buildDouble(builder, "ZOMBIE_BARREL_SPEED", 0.2);
        builder.pop();
        builder.push("Zombie Bruiser");
        this.ZOMBIE_BRUISER_ARMOR = buildDouble(builder, "ZOMBIE_BRUISER_ARMOR", 2.0);
        this.ZOMBIE_BRUISER_DAMAGE = buildDouble(builder, "ZOMBIE_BRUISER_DAMAGE", 6.0);
        this.ZOMBIE_BRUISER_HEALTH = buildDouble(builder, "ZOMBIE_BRUISER_HEALTH", 60.0);
        this.ZOMBIE_BRUISER_KNOCKBACK = buildDouble(builder, "ZOMBIE_BRUISER_KNOCKBACK", 3.6);
        this.ZOMBIE_BRUISER_KNOCKBACK_RESISTANCE = buildDouble(builder, "ZOMBIE_BRUISER_KNOCKBACK_RESISTANCE", 0.6);
        this.ZOMBIE_BRUISER_SPAWNING_ENABLED = buildBoolean(builder, "ZOMBIE_BRUISER_SPAWNING_ENABLED", true, ".");
        this.ZOMBIE_BRUISER_SPEED = buildDouble(builder, "ZOMBIE_BRUISER_SPEED", 0.26);
        builder.pop();
        builder.push("Zombie Clown");
        this.ZOMBIE_CLOWN_ARMOR = buildDouble(builder, "ZOMBIE_CLOWN_ARMOR", 4.0);
        this.ZOMBIE_CLOWN_DAMAGE = buildDouble(builder, "ZOMBIE_CLOWN_DAMAGE", 3.0);
        this.ZOMBIE_CLOWN_HEALTH = buildDouble(builder, "ZOMBIE_CLOWN_HEALTH", 35.0);
        this.ZOMBIE_CLOWN_KNOCKBACK = buildDouble(builder, "ZOMBIE_CLOWN_KNOCKBACK", 0.4);
        this.ZOMBIE_CLOWN_KNOCKBACK_RESISTANCE = buildDouble(builder, "ZOMBIE_CLOWN_KNOCKBACK_RESISTANCE", 0.5);
        this.ZOMBIE_CLOWN_SPAWNING_ENABLED = buildBoolean(builder, "ZOMBIE_CLOWN_SPAWNING_ENABLED", true, ".");
        this.ZOMBIE_CLOWN_SPEED = buildDouble(builder, "ZOMBIE_CLOWN_SPEED", 0.21);
        builder.pop();
        builder.push("Zombie Fisherman");
        this.ZOMBIE_FISHERMAN_ARMOR = buildDouble(builder, "ZOMBIE_FISHERMAN_ARMOR", 4.0);
        this.ZOMBIE_FISHERMAN_DAMAGE = buildDouble(builder, "ZOMBIE_FISHERMAN_DAMAGE", 4.0);
        this.ZOMBIE_FISHERMAN_HEALTH = buildDouble(builder, "ZOMBIE_FISHERMAN_HEALTH", 25.0);
        this.ZOMBIE_FISHERMAN_KNOCKBACK = buildDouble(builder, "ZOMBIE_FISHERMAN_KNOCKBACK", 0.4);
        this.ZOMBIE_FISHERMAN_KNOCKBACK_RESISTANCE = buildDouble(builder, "ZOMBIE_FISHERMAN_KNOCKBACK_RESISTANCE", 0.1);
        this.ZOMBIE_FISHERMAN_SPAWNING_ENABLED = buildBoolean(builder, "ZOMBIE_FISHERMAN_SPAWNING_ENABLED", true, ".");
        this.ZOMBIE_FISHERMAN_SPEED = buildDouble(builder, "ZOMBIE_FISHERMAN_SPEED", 0.2);
        builder.pop();
        builder.push("Zombie Lumberjack");
        this.ZOMBIE_LUMBERJACK_ARMOR = buildDouble(builder, "ZOMBIE_LUMBERJACK_ARMOR", 4.0);
        this.ZOMBIE_LUMBERJACK_DAMAGE = buildDouble(builder, "ZOMBIE_LUMBERJACK_DAMAGE", 9.0);
        this.ZOMBIE_LUMBERJACK_HEALTH = buildDouble(builder, "ZOMBIE_LUMBERJACK_HEALTH", 25.0);
        this.ZOMBIE_LUMBERJACK_KNOCKBACK = buildDouble(builder, "ZOMBIE_LUMBERJACK_KNOCKBACK", 0.3);
        this.ZOMBIE_LUMBERJACK_KNOCKBACK_RESISTANCE = buildDouble(builder, "ZOMBIE_LUMBERJACK_KNOCKBACK_RESISTANCE", 0.1);
        this.ZOMBIE_LUMBERJACK_SPAWNING_ENABLED = buildBoolean(builder, "ZOMBIE_LUMBERJACK_SPAWNING_ENABLED", true, ".");
        this.ZOMBIE_LUMBERJACK_SPEED = buildDouble(builder, "ZOMBIE_LUMBERJACK_SPEED", 0.2);

    }

    private static ForgeConfigSpec.BooleanValue buildBoolean(ForgeConfigSpec.Builder builder, String name, boolean defaultValue, String comment){
        return builder.comment(comment).translation(name).define(name, defaultValue);
    }

    private static ForgeConfigSpec.IntValue buildInt(ForgeConfigSpec.Builder builder, String name, int defaultValue, int min, int max, String comment){
        return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
    }

    private static ForgeConfigSpec.DoubleValue buildDouble(ForgeConfigSpec.Builder builder, String name, double defaultValue) {
        return builder.comment(".").translation(name).defineInRange(name, defaultValue, 0, Double.MAX_VALUE);
    }
}
